version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=skill
      - POSTGRES_PASSWORD=collector
      - POSTGRES_DB=testSkillData
    volumes:
      - postgres:/var/lib/postgresql/data
  skill-back:
    image: skill-back
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
      - 8181:8181
    volumes:
      - ./:/usr/src/app
    container_name: skill-back
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET=${SECRET_KEY}
    restart: always
  initdatabase:
    build: 
      context: ./
      dockerfile: dev.Dockerfile
    image: initdb
    stdin_open: true
    tty: true
    command: >
      sh -c "
      npx prisma db push
      && npx prisma db seed
      "
    depends_on:
      - skill-back
      - postgres
volumes:
  postgres:
## Some extra commands: 
## npx prisma db push && npx prisma db seed && npx prisma migrate dev --name init