# fly.toml app configuration file generated for skillback on 2023-07-23T13:39:47+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "skillback"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
