GET http://localhost:3000/api/results/soft HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMTIzIiwiaWF0IjoxNjgwMDc3ODY5LCJleHAiOjE2ODAwODE0Njl9.za4Nc0JVG7Vb4Bfge1y67GLNafAZBNlQ9yWLieV_SYU

